# Generated by Django 2.2.7 on 2019-11-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_auto_20191113_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemanagement',
            old_name='contactNo',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='employeemanagement',
            old_name='emailId',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='employeemanagement',
            old_name='employeeCode',
            new_name='employee_code',
        ),
    ]
