# Generated by Django 2.0.3 on 2019-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20191113_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='employee_code',
            field=models.CharField(max_length=6),
        ),
    ]
