# Generated by Django 2.0.3 on 2019-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_auto_20191114_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='employee_code',
            field=models.CharField(max_length=5),
        ),
    ]
