# Generated by Django 2.0.3 on 2019-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0007_auto_20191114_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='contact_no',
            field=models.CharField(max_length=40),
        ),
    ]
